### ISSUE TITLE
string fields are not parsed when numbers are set in cmd line.

### ISSUE THREAD

**Issue by maxence-charriere** [segmentio/conf#1]
conf example:
```go
type Config struct {
	Name             string `conf:"name" help:"Package name"`
	ID               string `conf:"id"   help:"UTI representing the app."`
}
```

if I launch my program like that:
```
myprog -id 42
myprog -id "42"
```
The usage description is displayed like if ```-h``` is used and instructions after ```conf.load``` are not called.

**Comment by achille-roussel** [comment]
Yeah that's an issue of using the yaml decoder for parsing the arguments, I'm planning on making some changes to support that.

**Comment by achille-roussel** [comment]
By the way you can work around it like this `myprog -id '"42"'` (otherwise your shell gets rid of the `"` in your example).
