### ISSUE TITLE
Personalize help output

### ISSUE THREAD

**Issue by maxence-charriere** [segmentio/conf#4]
It would be awesome if we can personalize the -h output.
I m in the case where I want to specify a command as parameter.
e.g.
```
gomac build -name MyProg
gomac run -v
```
I can retrieve the command with the result of ```conf.Load```
but if i don't find the command i want, I would like to print the help with a customized header like:
```
unknown command.

Usage:
   gomac [-h] [-help] [options...] [build | run]

Options:
... // The rest of the option output.
```

Have a way to set the usage would be nice.
Also is there a way to trigger manually the help output?

**Comment by achille-roussel** [comment]
Can you send a PR which addresses your need so we have a concrete example to discuss?

**Comment by maxence-charriere** [comment]
something like
```go
type Config struct {
    // fields.
}

func main() {
    var config Config

    conf.Usage = "gomac [build | run] [-h] [-help] [options...]"
    cmds := conf.Load(&config)
    
     if len(cmds) != 1 {
        fmt.Println("no cmd")
        conf.PrintHelp()
     }

    switch cmd := cmds[0]; cmd {
    case "build":
        // build job.
 
    case "run":
        // run job.
 
    default:
        fmt.Println("bad cmd:", cmd)
        conf.PrintHelp()
    }
}
```
